### ISSUE TITLE
Special characters not supported ?

### ISSUE THREAD

**Issue by Rdornier** [German-BioImaging/omero-autotag#10]
Hi, 

It seems that special characters like `#`, `+` are not supported. 
If a token contains one of these, it is not proposed in the list of tag candidates, even if the `show all potential tags` is activated, with rarity threshold = 1

![image](https://github.com/German-BioImaging/omero-autotag/assets/64911638/79eec77a-3fb2-4332-92bb-419f3a065b4b)

I was wondering if this behavior was intended or not. Creating manually a tag with such characters is allowed in the webclient.

Thanks,
Rémy.

Edit: If you create manually the tag with the special character in it, then the auto-tag plugin recongnizes that the tag already exists and proposes it as a candidate.

**Comment by Tom-TBT** [comment]
Hey Remy, took me a bit to understand why it showed `control-` instead but now I see it in the list bellow.

Indeed I see the same thing. I don't see why it would be an intended feature so I'll mark it as a bug. Thank you for reporting that
